# Generated by Django 3.2.12 on 2024-02-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20240206_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dota2Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_losses', models.IntegerField()),
                ('team_matches', models.IntegerField()),
                ('team_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dota2Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_position', models.CharField(max_length=100)),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dota2teams')),
            ],
        ),
    ]
