# Generated by Django 3.2.12 on 2024-02-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dota2players_dota2teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dota2Players',
        ),
        migrations.DeleteModel(
            name='Dota2Teams',
        ),
    ]
