# Generated by Django 4.0 on 2024-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota2teams',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
